layout_spectrum: 1
color:
  saturation: 0.9392917
  lightness: 0.737774
  brandStrength: 0.7951096
  rhythmicContrast: 0.822091
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.4187351
name: Iamworship
